<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>FastCom.Domain</RootNamespace>
  </PropertyGroup>

  <!-- ⭐ Domain من غير أي Dependencies — دي أنضف طبقة في المشروع -->
  <ItemGroup>
    <ProjectReference Include="..\FastCom.Shared\FastCom.Shared.csproj" />
  </ItemGroup>

</Project>
