/* =====================================================================================
   FastCom - Table Inventory
   ------------------------------------------------------------------------------------
   بيقارن الـ 68 جدول المتوقعين باللي موجود فعلا في قاعدة البيانات.

   شغّله في SSMS - هيرجع 2 نتيجة:
     1. كل الجداول الناقصة (MISSING)
     2. ملخص الاعداد
   ===================================================================================== */

SET NOCOUNT ON;

/* ── 1) الجداول الناقصة ─────────────────────────────────────────────────────── */
SELECT
    ROW_NUMBER() OVER (ORDER BY e.ExpectedTable) AS [#],
    e.ExpectedTable                              AS [Table],
    CASE WHEN t.object_id IS NULL
         THEN N'-- MISSING --'
         ELSE N'OK'
    END                                          AS [Status]
FROM (VALUES
    (N'Branches'),
    (N'CompanyProfile'),
    (N'Departments'),
    (N'JobTitles'),
    (N'SystemSettings'),
    (N'DocumentTypes'),
    (N'PaymentTerms'),
    (N'PaymentMethods'),
    (N'TaxRates'),
    (N'Ports'),
    (N'Destinations'),
    (N'TripTypes'),
    (N'Services'),
    (N'ContainerTypes'),
    (N'ExpenseTypes'),
    (N'OperationStatuses'),
    (N'Customers'),
    (N'CustomerContacts'),
    (N'Suppliers'),
    (N'Employees'),
    (N'Drivers'),
    (N'Vehicles'),
    (N'Trailers'),
    (N'VehicleMaintenance'),
    (N'PriceLists'),
    (N'CustomerPriceRules'),
    (N'Bookings'),
    (N'Containers'),
    (N'ContainerMovements'),
    (N'BookingContainerLines'),
    (N'BookingContainerDetails'),
    (N'Operations'),
    (N'Trips'),
    (N'TripOperations'),
    (N'TripCostAllocations'),
    (N'OperationContainers'),
    (N'OperationRevenueItems'),
    (N'DriverCustodies'),
    (N'CustodyTransactions'),
    (N'Expenses'),
    (N'Invoices'),
    (N'InvoiceItems'),
    (N'InvoiceOperations'),
    (N'Payments'),
    (N'PaymentAllocations'),
    (N'InvoiceSendLogs'),
    (N'SupplierInvoices'),
    (N'SupplierInvoiceItems'),
    (N'SupplierPayments'),
    (N'SupplierInvoiceAllocations'),
    (N'CashBoxes'),
    (N'CashTransactions'),
    (N'Documents'),
    (N'Notifications'),
    (N'CustomerPortalTokens'),
    (N'PortalAccessLogs'),
    (N'AspNetRoles'),
    (N'AspNetUsers'),
    (N'AspNetUserRoles'),
    (N'AspNetUserClaims'),
    (N'AspNetUserLogins'),
    (N'AspNetUserTokens'),
    (N'AspNetRoleClaims'),
    (N'AppPermissions'),
    (N'AppRolePermissions'),
    (N'AppUserPermissions'),
    (N'AuditLogs'),
    (N'NumberSequences')
) AS e(ExpectedTable)
LEFT JOIN sys.tables t ON t.name = e.ExpectedTable
ORDER BY e.ExpectedTable;

/* ── 2) الملخص ──────────────────────────────────────────────────────────────── */
WITH Expected(ExpectedTable) AS (
    VALUES
    (N'Branches'),
    (N'CompanyProfile'),
    (N'Departments'),
    (N'JobTitles'),
    (N'SystemSettings'),
    (N'DocumentTypes'),
    (N'PaymentTerms'),
    (N'PaymentMethods'),
    (N'TaxRates'),
    (N'Ports'),
    (N'Destinations'),
    (N'TripTypes'),
    (N'Services'),
    (N'ContainerTypes'),
    (N'ExpenseTypes'),
    (N'OperationStatuses'),
    (N'Customers'),
    (N'CustomerContacts'),
    (N'Suppliers'),
    (N'Employees'),
    (N'Drivers'),
    (N'Vehicles'),
    (N'Trailers'),
    (N'VehicleMaintenance'),
    (N'PriceLists'),
    (N'CustomerPriceRules'),
    (N'Bookings'),
    (N'Containers'),
    (N'ContainerMovements'),
    (N'BookingContainerLines'),
    (N'BookingContainerDetails'),
    (N'Operations'),
    (N'Trips'),
    (N'TripOperations'),
    (N'TripCostAllocations'),
    (N'OperationContainers'),
    (N'OperationRevenueItems'),
    (N'DriverCustodies'),
    (N'CustodyTransactions'),
    (N'Expenses'),
    (N'Invoices'),
    (N'InvoiceItems'),
    (N'InvoiceOperations'),
    (N'Payments'),
    (N'PaymentAllocations'),
    (N'InvoiceSendLogs'),
    (N'SupplierInvoices'),
    (N'SupplierInvoiceItems'),
    (N'SupplierPayments'),
    (N'SupplierInvoiceAllocations'),
    (N'CashBoxes'),
    (N'CashTransactions'),
    (N'Documents'),
    (N'Notifications'),
    (N'CustomerPortalTokens'),
    (N'PortalAccessLogs'),
    (N'AspNetRoles'),
    (N'AspNetUsers'),
    (N'AspNetUserRoles'),
    (N'AspNetUserClaims'),
    (N'AspNetUserLogins'),
    (N'AspNetUserTokens'),
    (N'AspNetRoleClaims'),
    (N'AppPermissions'),
    (N'AppRolePermissions'),
    (N'AppUserPermissions'),
    (N'AuditLogs'),
    (N'NumberSequences')
)
SELECT
    (SELECT COUNT(*) FROM Expected)                                        AS [Expected_Tables],
    (SELECT COUNT(*) FROM sys.tables)                                      AS [Actual_Tables],
    (SELECT COUNT(*) FROM Expected e
      WHERE NOT EXISTS (SELECT 1 FROM sys.tables t WHERE t.name = e.ExpectedTable))
                                                                           AS [Missing],
    (SELECT COUNT(*) FROM sys.views)                                       AS [Views],
    (SELECT COUNT(*) FROM sys.triggers WHERE is_ms_shipped = 0)            AS [Triggers],
    (SELECT COUNT(*) FROM sys.procedures WHERE is_ms_shipped = 0)          AS [Procedures],
    (SELECT COUNT(*) FROM AppPermissions)                                  AS [Permissions],
    (SELECT COUNT(*) FROM AspNetRoles)                                     AS [Roles];
